### ISSUE TITLE
Xcode 9.3.1  不能 运行插件

### ISSUE THREAD

**Issue by xyhuangjia** [ame017/AMEGetterMaker#1]

**Comment by ame017** [comment]
不会的呀，这个跟以前那种插件不一样,是版本通用的

**Comment by xyhuangjia** [comment]
安装后在拓展中显示不出来，运行源代码也是显示不出插件，很诡异

**Comment by xyhuangjia** [comment]
@ame017 安装后在拓展中显示不出来，运行源代码也是显示不出插件，很诡异

**Comment by ame017** [comment]
@xyhuangjia 更新下你的macOS系统试试

**Comment by xyhuangjia** [comment]
@ame017 已经是最新的了，但是我的本本上的就没有问题

**Comment by ame017** [comment]
@xyhuangjia 这个我也不清楚了，可能是系统级的bug吧
